In [3]:
# 파이썬 리스트랑 NumPy의 가장 큰 차이

# 파이썬 리스트 :
numbers = [1, 2, 3, 4]

print(numbers * 2)
# 결과 :
# [1, 2, 3, 4, 1, 2, 3, 4]

# NumPy는?
import numpy as np

numbers = np.array([1, 2, 3, 4])

print(numbers * 2)
# 결과 :
#[2 4 6 8]

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [5]:
# Numpy 배열 만들기
import numpy as np

arr = np.array([10, 20, 30])

print(arr)
print(type(arr))

[10 20 30]
<class 'numpy.ndarray'>


In [ ]:
# 배열 전체 연산
import numpy as np

arr = np.array([10, 20, 30])

print(arr + 10)
# 즉 for문 없이 배열 전체에 계산 적용 가능
# = 벡터화 연산( Vectorized Operation )

[20 30 40]


In [7]:
# 배열끼리 연산도 가능
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)

[11 22 33]


In [8]:
# 인덱싱과 슬라이싱은 리스트와 유사
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr[0])
print(arr[2])
print(arr[1:3])

10
30
[20 30]


In [ ]:
# NumPy가 ML에서 중요한 이유
import numpy as np

# 예를 들어 학생 점수가

scores = np.array([90, 80, 70, 60])

# 100점 기준으로 0~1 사이 값으로 바꾸고 싶으면:
normalized_score = scores / 100

# 결과
print(normalized_score)
# [0.9 0.8 0.7 0.6]

In [9]:
# 연습문제 1
import numpy as np

scores = np.array([50, 70, 80, 90])

normalized_scores = scores / 100

print(normalized_scores)

[0.5 0.7 0.8 0.9]


In [15]:
# 연습문제 2
import numpy as np

scores = np.array([50, 70, 80, 90])

passed_scores = scores[scores >= 70]

print(passed_scores)

[70 80 90]
