In [ ]:
# 연습문제 3-1(불린 인덱싱)
# numpy 호출
import numpy as np

# 1차원 배열 생성
scores = np.array([50, 70, 80, 90])

# 불린 인덱싱을 이용해 70점 이상인 점수에 True, 나머지 점수에 False를 저장한 배열을 만듦
ispassed = scores >= 70

# 불린 인덱싱을 사용해 70점 이상인 점수, 즉 True에 해당하는 필드만 저장하는 새 배열을 만듦
passed_scores = scores[ispassed]
print(passed_scores)

In [ ]:
# 연습문제 3-2(불린 인덱싱 2)
# numpy 호출
import numpy as np

# 1차원 배열 생성
scores = np.array([50, 70, 80, 90])

# 불린 인덱싱을 이용해 70점 이상인 점수에 True, 나머지는 False를 저장한 새 배열을 보고 True에 해당하는 필드만 저장한 새 배열을 만듦
scores = scores[scores >= 70]
# 출력
print(scores)

In [ ]:
# Numpy를 호출
import numpy as np

# 1차원 배열 생성
scores = np.array([0.91, 0.32, 0.82, 0.95, 0.42, 0.83, 0.68])
# 0.8 이상인 점수만 여부를 저장한 새 배열 생성
is_passed = scores >= 0.8
# 0.5 미만인 점수만 여부를 저장한 새 배열 생성
is_failed = scores < 0.5
# 1차원 배열의 전체 평균을 저장한 변수 생성
avg_score = scores.mean()
# 1차원 배열의 최대값을 저장한 변수 생성
max_score = scores.max()
# 1차원 배열의 최소값을 저장한 변수 생성
min_score = scores.min()
# 1차원 배열의 평균 이상인 점수만 여부를 저장한 새 배열 생성
is_overed_avg = scores > avg_score

# 불린 인덱싱을 사용해 0.8 이상인 점수만 저장한 새 배열 생성
passed_scores = scores[is_passed]
# 불린 인덱싱을 사용해 0.5 미만인 점수만 저장한 새 배열 생성
failed_scores = scores[is_failed]
# 불린 인덱싱을 사용해 평균 이상인 점수만 저장한 새 배열 생성
overed_avg = scores[is_overed_avg]
# 0.8 이상인 점수의 개수를 저장한 변수 생성
ispassed_sum = is_passed.sum()
# 0.8 이상인 점수의 평균을 저장한 변수 생성
ispassed_mean = is_passed.mean()
# 0.5 미만인 점수의 비율을 저장한 변수 생성
isfailed_mean = is_failed.mean()
# 0.5 미만이거나 0.8 이상인 점수의 여부를 저장한 새 배열 생성
is_middle = (scores < 0.5) | (scores >= 0.8)
# 불린 인덱싱을 사용해 0.5 미만이거나 0.8 이상의 점수를 저장한 새 배열 생성
middle_scores = scores[is_middle]


print(passed_scores)
print(failed_scores)
print(avg_score)
print(max_score)
print(min_score)
print(overed_avg)
print(ispassed_sum)
print(ispassed_mean)
print(isfailed_mean)
# 0.5 미만인 점수들의 평균을 저장한 변수 출력
print(failed_scores.mean())
print(middle_scores)

[0.91 0.82 0.95 0.83]
[0.32 0.42]
0.7042857142857143
0.95
0.32
[0.91 0.82 0.95 0.83]
4
0.5714285714285714
0.2857142857142857
0.37
[0.91 0.32 0.82 0.95 0.42 0.83]
